name: flutter_twitch_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  internet_connection_checker: ^0.0.1+4
  http: ^0.13.4
  get_storage: ^2.0.3
  get_it: ^7.2.0
  flutter_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  font_awesome_flutter: '>= 4.7.0'
  carousel_slider: ^4.1.1
  webview_flutter: ^3.0.4
  firebase_dynamic_links: ^4.2.5
  firebase_core: ^1.17.1
  web_socket_channel: ^2.2.0
  shimmer: ^2.0.0
  sticky_headers: ^0.3.0+2
  awesome_notifications: any
  floating_draggable_widget: ^2.0.0
  animations: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/
