// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI7kfWYUwDHQwVSsgR9uO7emvk2YdRqEI',
    appId: '1:23923310522:android:945b0aa9e4c8ff7a71e783',
    messagingSenderId: '23923310522',
    projectId: 'fir-demo-8bb64',
    storageBucket: 'fir-demo-8bb64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANfEDK81j6n-KfFj6H4owa_SRrfdfsdFo',
    appId: '1:23923310522:ios:c2376b2c64e2e26f71e783',
    messagingSenderId: '23923310522',
    projectId: 'fir-demo-8bb64',
    storageBucket: 'fir-demo-8bb64.appspot.com',
    androidClientId: '23923310522-q0bv54hgiito4l84je7o2kijqsapd7df.apps.googleusercontent.com',
    iosClientId: '23923310522-ugp5g2r7dscbqopgs64rmi78r09dkikd.apps.googleusercontent.com',
    iosBundleId: 'asia.executionlab.flutterTwitchClone',
  );
}
